### ISSUE TITLE
crickit for microbit

### ISSUE THREAD

**Issue by ladyada** [adafruit/pxt-crickit#8]
@pelikhan i have the crickit:bit ready for testing, works great in arduino, time to test in makecode - how can we enable this pkg for 'bits?

**Comment by pelikhan** [comment]
Let me do some investigation to see the gaps with the micro:bit API set.

**Comment by pelikhan** [comment]
Ok there's a bunch of API that we need to port to make this work. It's probably going to take a week.

**Comment by ladyada** [comment]
! ok for some reason i thought the underlying stuff was all identical. shows what i know :D i will await further command

https://twitter.com/adafruit/status/1004124563729469441

**Comment by pelikhan** [comment]
The micro:bit editor is still currently on a v0 branch of PXT (without floating point and stuff) so it has evolved quite differently from the Adafruit branch.
I don't think there's anything major that's blocking but I need to make sure we've gotten the same abstractions in place on both side (like I2cDevice, Math.map are missing). I am probably make the change in the v1 branch of micro:bit then backport this to v0 later on.

**Comment by ladyada** [comment]
oooh ok. the more you know! :)

**Comment by pelikhan** [comment]
So part one is done: seesaw for microbit -- https://github.com/adafruit/pxt-seesaw/pull/10

Sharing code for crickit is going to be a bit more challenging as the block integration is signifantly different.

**Comment by ladyada** [comment]
ok thank you! i was planning on making a feather-to-microbit adapter and that would let people use the vast # of feathers we've got...but again the code is in python. would we have to go thru the same process to post-adapt pyconv code?

**Comment by pelikhan** [comment]
Yes the pyconv converter gives a good headstart.

**Comment by ladyada** [comment]
iz done and tested/doc'd
